server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:naishanZheng/springcloud-config2.git   #GitHub S上面的git仓库名字
          force-pull: true
#server:
#  port: 3344

#spring:
#  application:
#    name: microservicecloud-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/naishanZheng/springCloud-config.git
#          search-paths: config-repo
#          username: naishanZheng  #账号密码写真实的快一些我觉得，不使用也能访问有点慢
#          password: qqaw+13543571932
#          force-pull: true